# Generated by Django 3.2 on 2023-01-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(choices=[('ACTOR', 'actor'), ('DIRECTOR', 'director'), ('WRITER', 'writer')], max_length=255, verbose_name='role'),
        ),
    ]
