version: '3'
services:
  db:
    image: postgres:13
    restart: always
    container_name: postgres_etl
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - ./.env

  elasticsearch:
    image: elasticsearch:7.9.1
    container_name: elasticsearch_etl
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - my_network

  redis:
    image: redis
    container_name: redis_etl
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_volume:
